SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , GENDER
     , COUNT(DISTINCT s.USER_ID) AS USERS
FROM USER_INFO i 
JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE) , MONTH(SALES_DATE) , GENDER
ORDER BY YEAR(SALES_DATE) , MONTH(SALES_DATE) , GENDER
