SELECT b.ANIMAL_ID
     , b.ANIMAL_TYPE
     , b.NAME
FROM ANIMAL_INS a 
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE LIKE 'Intact%' 
    AND (b.SEX_UPON_OUTCOME LIKE 'Spayed%' or b.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID
