SELECT b.USER_ID 
     , b.NICKNAME 
     , CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소'
     , CONCAT(left(TLNO,3),'-',mid(TLNO,4,4),'-',right(TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD a 
JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
GROUP BY a.WRITER_ID
HAVING COUNT(*) > 2
ORDER BY b.USER_ID DESC
